### ISSUE TITLE
能提供下数据集的下载链接吗

### ISSUE THREAD

**Issue by wind91725** [jingyihiter/mycail#1]
您好 我想拿到这个比赛的数据集 可是官网 已经停止注册了 能麻烦您 提供一下 下载链接吗 十分感谢

**Comment by jingyihiter** [comment]
问一下官方吧，我复制不了下载链接。而且下载链接估计也得登陆才有效,官方qq群237633234

**Comment by wind91725** [comment]
哦哦好的 谢谢啦 我还以为 这数据集已经公开了呢

**Comment by jingyihiter** [comment]
不客气
